name: "Semantic Release"
description: "Run semantic-release to automate versioning, changelog, and releases"
inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "18"
  npm-token:
    description: "NPM token for publishing packages (optional)"
    required: false
  github-token:
    description: "GitHub token with repo write permissions"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # required for semantic-release to read tags

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Run semantic-release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
      run: npx semantic-release
